BackendBundle\Entity\Comment:
    type: entity
    table: comments
    indexes:
        fk_comment_video:
            columns:
                - video_id
        fk_comment_user:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        body:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        video:
            targetEntity: Video
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                video_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
