comment_new:           
    path:   /new
    defaults: { _controller: "AppBundle:Comment:new"}
    methods:  POST
    
comment_delete:           
    path:   /delete/{id}
    defaults: { _controller: "AppBundle:Comment:delete", id: null }
    methods:  POST
    
comment_list:           
    path:   /list/{id}
    defaults: { _controller: "AppBundle:Comment:list", id: null }
    methods:  GET